"""Renderer for a local ComfyUI server via its REST API."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/08_renderers/comfyui.ipynb.

# %% ../../nbs/08_renderers/comfyui.ipynb #cell-3
from __future__ import annotations
import json
import time
import uuid
from pathlib import Path

import httpx

from ..config import OutputConfig, RendererConfig
from ..models import Panel, RenderResult
from ..render import BaseRenderer, ModelSpec

# %% auto #0
__all__ = ['ComfyUIRenderer']

# %% ../../nbs/08_renderers/comfyui.ipynb #cell-4
# Node titles used to patch the TextToImage workflow template.
# These must match the _meta.title values in your ComfyUI workflow.
_PROMPT_NODE_TITLE = "positive_prompt"
_NEGATIVE_NODE_TITLE = "negative_prompt"
_WIDTH_NODE_TITLE = "empty_latent_image"       # direct width/height inputs
_WIDTH_PRIMITIVE_NODE_TITLE = "Width"           # PrimitiveInt node for width
_HEIGHT_PRIMITIVE_NODE_TITLE = "Height"         # PrimitiveInt node for height
_LORA_NODE_TITLE = "lora_loader"
_REF_IMAGE_NODE_TITLE = "reference_image"

# Node titles used to patch the SpeechBubble workflow template.
_SPEECH_BUBBLE_INPUT_IMAGE_TITLE = "bubble_input_image"
_SPEECH_BUBBLE_TEXT_TITLE = "bubble_text"


def _find_panel_image(panels_dir: Path, panel_number: int) -> Path | None:
    """Return the path of an existing panel image, trying common formats."""
    for ext in ("png", "jpg", "webp"):
        p = panels_dir / f"panel_{panel_number:04d}.{ext}"
        if p.exists():
            return p
    return None


def _print_panel_timing(progress, panel_num: int, elapsed: float, avg: float, eta_s: float) -> None:
    """Print the per-panel timing line to the progress console."""
    eta_str = f"{int(eta_s // 60)}m {int(eta_s % 60)}s" if eta_s >= 60 else f"{eta_s:.0f}s"
    progress.console.print(
        f"  [dim]panel {panel_num:04d}[/dim]  "
        f"[green]{elapsed:.1f}s[/green]  "
        f"avg [cyan]{avg:.1f}s[/cyan]/panel  "
        f"ETA [yellow]{eta_str}[/yellow]"
    )


async def _eta_tick(progress, task_id: int, eta_deadline: list) -> None:
    """Count down the ETA progress bar field every second from eta_deadline."""
    import asyncio as _asyncio
    import time as _t
    while True:
        await _asyncio.sleep(1)
        if eta_deadline[0] > 0:
            remaining_s = max(0.0, eta_deadline[0] - _t.monotonic())
            mins, secs = divmod(int(remaining_s), 60)
            progress.update(task_id, eta=f"{mins}m {secs}s" if mins else f"{secs}s")

# %% ../../nbs/08_renderers/comfyui.ipynb #cell-5
class ComfyUIRenderer(BaseRenderer):
    """Image generation via a local ComfyUI server.

    The panel image is generated by the TextToImage workflow. Speech bubbles
    are applied as a separate post-processing step via ``add_speech_bubbles_batch_async``.

    Config:
        renderer.comfyui.base_url                    — ComfyUI server URL
        renderer.comfyui.workflow_template_path       — TextToImage workflow JSON
        renderer.comfyui.speech_bubble_workflow_path  — Speech bubble workflow JSON (optional)
        renderer.comfyui.poll_interval               — seconds between status checks
        renderer.comfyui.timeout                     — max wait seconds per panel
    """

    def __init__(self, model_spec: ModelSpec, config: RendererConfig):
        super().__init__(model_spec, config)
        self._model_cfg = config.comfyui
        self._workflow_template: dict | None = None
        self._speech_bubble_template: dict | None = None

    # ── Workflow loading ─────────────────────────────────────────────────────

    def _load_workflow(self) -> dict:
        if self._workflow_template is None:
            path = Path(self._model_cfg.workflow_template_path)
            if not path.exists():
                raise FileNotFoundError(
                    f"ComfyUI workflow not found: {path}. "
                    f"Set renderer.comfyui.workflow_template_path in your config."
                )
            self._workflow_template = json.loads(path.read_text())
        return json.loads(json.dumps(self._workflow_template))  # deep copy

    def _load_speech_bubble_workflow(self) -> dict | None:
        """Load the speech bubble workflow template, or None if not configured."""
        path_str = self._model_cfg.speech_bubble_workflow_path
        if not path_str:
            return None
        path = Path(path_str)
        if not path.exists():
            return None
        if self._speech_bubble_template is None:
            self._speech_bubble_template = json.loads(path.read_text())
        return json.loads(json.dumps(self._speech_bubble_template))  # deep copy

    # ── Workflow patching ────────────────────────────────────────────────────

    def _build_patch_map(
        self,
        panel: Panel,
        w: int,
        h: int,
        negative_prompt: str,
        reference_image_b64: str | None,
    ) -> dict:
        """Return a {node_title: patch_fn(inputs)} map for the TextToImage workflow."""
        patches: dict = {
            _PROMPT_NODE_TITLE:           lambda inp: inp.__setitem__("text", panel.visual_prompt) if "text" in inp else None,
            _NEGATIVE_NODE_TITLE:         lambda inp: inp.__setitem__("text", negative_prompt) if "text" in inp else None,
            _WIDTH_NODE_TITLE:            lambda inp: inp.update({k: v for k, v in {"width": w, "height": h}.items() if k in inp}),
            _WIDTH_PRIMITIVE_NODE_TITLE:  lambda inp: inp.__setitem__("value", w) if "value" in inp else None,
            _HEIGHT_PRIMITIVE_NODE_TITLE: lambda inp: inp.__setitem__("value", h) if "value" in inp else None,
        }
        if self.config.loras:
            lora = self.config.loras[0]
            patches[_LORA_NODE_TITLE] = lambda inp: inp.update(
                {k: v for k, v in {"lora_name": lora.path, "strength_model": lora.strength}.items() if k in inp}
            )
        if reference_image_b64:
            patches[_REF_IMAGE_NODE_TITLE] = lambda inp: inp.__setitem__("image", reference_image_b64) if "image" in inp else None
        return patches

    def _patch_workflow(
        self,
        workflow: dict,
        panel: Panel,
        output_cfg: OutputConfig,
        negative_prompt: str = "",
        reference_image_b64: str | None = None,
    ) -> dict:
        """Patch TextToImage workflow nodes with panel-specific values."""
        w, h = output_cfg.resolved_dimensions()
        patches = self._build_patch_map(panel, w, h, negative_prompt, reference_image_b64)
        for node in workflow.values():
            title = node.get("_meta", {}).get("title", "")
            patch_fn = patches.get(title)
            if patch_fn:
                patch_fn(node.get("inputs", {}))
        return workflow

    def _patch_speech_bubble_workflow(
        self,
        workflow: dict,
        image_filename: str,
        dialogue_text: str,
    ) -> dict:
        """Patch the speech bubble workflow with the panel image and dialogue."""
        for node in workflow.values():
            title = node.get("_meta", {}).get("title", "")
            inputs = node.get("inputs", {})
            if title == _SPEECH_BUBBLE_INPUT_IMAGE_TITLE and "image" in inputs:
                inputs["image"] = image_filename
            elif title == _SPEECH_BUBBLE_TEXT_TITLE and "text" in inputs:
                inputs["text"] = dialogue_text
        return workflow

    # ── ComfyUI HTTP helpers ─────────────────────────────────────────────────

    def _submit_and_wait(self, workflow: dict) -> bytes:
        """Submit a workflow to ComfyUI and poll until the image is ready."""
        base = self._model_cfg.base_url.rstrip("/")
        client_id = str(uuid.uuid4())

        resp = httpx.post(
            f"{base}/prompt",
            json={"prompt": workflow, "client_id": client_id},
            timeout=30,
        )
        resp.raise_for_status()
        prompt_id = resp.json()["prompt_id"]

        deadline = time.time() + self._model_cfg.timeout
        while time.time() < deadline:
            time.sleep(self._model_cfg.poll_interval)
            history = httpx.get(f"{base}/history/{prompt_id}", timeout=10).json()
            if prompt_id in history:
                outputs = history[prompt_id].get("outputs", {})
                for node_output in outputs.values():
                    images = node_output.get("images", [])
                    if images:
                        img_info = images[0]
                        img_resp = httpx.get(
                            f"{base}/view",
                            params={"filename": img_info["filename"],
                                    "subfolder": img_info.get("subfolder", ""),
                                    "type": img_info.get("type", "output")},
                            timeout=30,
                        )
                        img_resp.raise_for_status()
                        return img_resp.content

        raise TimeoutError(f"ComfyUI job {prompt_id} did not complete within {self._model_cfg.timeout}s")

    def _upload_image(self, image_path: Path) -> str:
        """Upload a local image to ComfyUI's input folder. Returns the filename."""
        base = self._model_cfg.base_url.rstrip("/")
        with open(image_path, "rb") as f:
            resp = httpx.post(
                f"{base}/upload/image",
                files={"image": (image_path.name, f, "image/png")},
                timeout=30,
            )
        resp.raise_for_status()
        return resp.json()["name"]

    # ── Speech bubble step ───────────────────────────────────────────────────

    @staticmethod
    def _bubble_prompt(speaker: str, text: str, bubble_type: str, bubble_types: dict) -> str:
        """Return a visual description for one dialogue bubble using the template dict."""
        t = bubble_type.lower()
        if speaker.lower() == "narration":
            t = "caption"
        template = bubble_types.get(t) or bubble_types.get("speech") or ""
        return template.format(speaker=speaker, text=text)

    def _apply_speech_bubbles(
        self,
        panel: Panel,
        image_path: Path,
        bubble_types: dict,
    ) -> bytes | None:
        """Run the speech bubble workflow on the given panel image.

        Returns the new image bytes, or None if no workflow is configured.
        """
        workflow = self._load_speech_bubble_workflow()
        if workflow is None:
            return None

        image_filename = self._upload_image(image_path)
        entries = panel.dialogue or []
        n = len(entries)
        bubble_lines = [self._bubble_prompt(b.speaker, b.text, b.bubble_type, bubble_types) for b in entries]
        header = (
            f"CRITICAL RULE: add EXACTLY {n} speech element{'s' if n != 1 else ''} to this image — "
            f"no more, no less. Do not add any extra bubbles, text, labels, or visual elements.\n\n"
        )
        dialogue_text = header + "\n".join(f"{i+1}. {line}" for i, line in enumerate(bubble_lines)) if entries else ""

        workflow = self._patch_speech_bubble_workflow(workflow, image_filename, dialogue_text)
        return self._submit_and_wait(workflow)

    # ── Batch speech bubbles ─────────────────────────────────────────────────

    async def add_speech_bubbles_batch_async(
        self,
        panels: list,
        panels_dir: Path,
        resume: bool = True,
        bubble_types: dict | None = None,
        verbose: bool = True,
    ) -> list[Path]:
        """Apply speech bubbles to a batch of already-rendered panel images.

        Looks up each panel image in ``panels_dir`` by panel number, uploads it
        to ComfyUI, runs the speech bubble workflow on top, and overwrites the
        file in-place.  Panels with no dialogue are silently skipped.

        Args:
            panels: List of Panel objects (from storyboard).
            panels_dir: Directory containing the rendered panel images.
            resume: If True, skip panels whose images already have a
                    ``<stem>.bubbles_done`` marker file next to them.

        Returns:
            List of image Paths that were updated.

        Raises:
            FileNotFoundError: If no speech bubble workflow is configured.
        """
        import asyncio
        import time as _time
        from rich.progress import BarColumn, MofNCompleteColumn, Progress, SpinnerColumn, TextColumn, TimeElapsedColumn
        from rich.console import Console

        _con = Console()

        if self._load_speech_bubble_workflow() is None:
            raise FileNotFoundError(
                "No speech bubble workflow configured. "
                "Set renderer.comfyui.speech_bubble_workflow_path in your config."
            )

        dialogue_panels = [p for p in panels if p.dialogue]
        total = len(dialogue_panels)

        sem = asyncio.Semaphore(2)
        last_finish: list[float] = [_time.monotonic()]
        finish_lock = asyncio.Lock()
        completed_times: list[float] = []
        eta_deadline: list[float] = [0.0]  # monotonic timestamp when ETA hits zero

        with Progress(
            SpinnerColumn(),
            TextColumn("[bold cyan]bubbles[/bold cyan]"),
            BarColumn(),
            MofNCompleteColumn(),
            TimeElapsedColumn(),
            TextColumn("·"),
            TextColumn("[yellow]{task.fields[eta]}[/yellow]"),
            console=_con,
            transient=False,
        ) as progress:
            task = progress.add_task("", total=total, eta="--:--")

            _bt = bubble_types or {}

            async def _process(panel) -> Path | None:
                img_path = _find_panel_image(panels_dir, panel.panel_number)
                if img_path is None:
                    progress.advance(task)
                    return None

                marker = img_path.with_suffix(".bubbles_done")
                if resume and marker.exists():
                    progress.advance(task)
                    return img_path

                # Keep a clean backup of the rendered image before any bubbles are
                # applied. On re-runs we always use this backup as the source so
                # bubbles are never stacked on top of each other.
                raw_path = img_path.parent / (img_path.stem + ".raw" + img_path.suffix)
                if not raw_path.exists():
                    import shutil as _shutil
                    _shutil.copy2(img_path, raw_path)
                source_path = raw_path

                async with sem:
                    bubble_bytes = await asyncio.get_event_loop().run_in_executor(
                        None, lambda: self._apply_speech_bubbles(panel, source_path, _bt)
                    )
                if bubble_bytes is None:
                    progress.advance(task)
                    return None

                img_path.write_bytes(bubble_bytes)
                marker.touch()

                async with finish_lock:
                    now = _time.monotonic()
                    elapsed = now - last_finish[0]
                    last_finish[0] = now
                    completed_times.append(elapsed)
                    avg = sum(completed_times[1:]) / len(completed_times[1:]) if len(completed_times) > 1 else completed_times[0]
                    remaining = total - (progress.tasks[task].completed + 1)
                    eta_deadline[0] = _time.monotonic() + avg * remaining
                    if verbose:
                        _print_panel_timing(progress, panel.panel_number, elapsed, avg, avg * remaining)
                    progress.advance(task)
                return img_path

            tick_task = asyncio.create_task(_eta_tick(progress, task, eta_deadline))
            try:
                results = await asyncio.gather(
                    *[_process(p) for p in dialogue_panels],
                    return_exceptions=True,
                )
            finally:
                tick_task.cancel()
                await asyncio.gather(tick_task, return_exceptions=True)

        return [r for r in results if r is not None]

    # ── Rendering ────────────────────────────────────────────────────────────

    async def render_async(
        self,
        panel: Panel,
        output_dir: Path,
        output_cfg: OutputConfig,
        reference_images: dict[str, Path] | None = None,
        negative_prompt: str = "",
    ) -> RenderResult:
        import asyncio
        return await asyncio.get_event_loop().run_in_executor(
            None, self._render_sync, panel, output_dir, output_cfg, reference_images, negative_prompt
        )

    def _render_sync(
        self,
        panel: Panel,
        output_dir: Path,
        output_cfg: OutputConfig,
        reference_images: dict[str, Path] | None,
        negative_prompt: str = "",
    ) -> RenderResult:
        import base64

        workflow = self._load_workflow()

        ref_b64: str | None = None
        if reference_images:
            for char_name in panel.characters_present:
                ref_path = reference_images.get(char_name)
                if ref_path and ref_path.exists():
                    ref_b64 = base64.b64encode(ref_path.read_bytes()).decode()
                    break

        workflow = self._patch_workflow(workflow, panel, output_cfg, negative_prompt, ref_b64)
        image_bytes = self._submit_and_wait(workflow)

        out_path = output_dir / f"panel_{panel.panel_number:04d}.{output_cfg.format}"
        out_path.write_bytes(image_bytes)

        return RenderResult(
            panel_number=panel.panel_number,
            image_path=out_path,
            backend_used=self.model_spec.name,
            prompt_used=panel.visual_prompt,
            metadata={
                "ref_image_used": ref_b64 is not None,
                "loras": len(self.config.loras),
            },
        )
