"""Renderer for Flux Klein 9B via Replicate."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/08_renderers/flux_klein.ipynb.

# %% ../../nbs/08_renderers/flux_klein.ipynb #cell-3
from __future__ import annotations
import os
from pathlib import Path

from ..config import OutputConfig, RendererConfig
from ..models import Panel, RenderResult
from ..render import BaseRenderer, ModelSpec

# %% auto #0
__all__ = ['FluxKleinRenderer']

# %% ../../nbs/08_renderers/flux_klein.ipynb #cell-4
class FluxKleinRenderer(BaseRenderer):
    """Image generation via Flux Klein 9B on Replicate.

    Supports LoRA weights and negative prompts.
    No reference image input — character consistency via text prompts only.

    Requires: REPLICATE_API_TOKEN environment variable.
    Config: renderer.flux_klein.model_ref (Replicate model string)
    """

    def __init__(self, model_spec: ModelSpec, config: RendererConfig):
        super().__init__(model_spec, config)
        self._model_cfg = config.flux_klein

    def _client(self):
        import replicate  # type: ignore
        if not os.environ.get("REPLICATE_API_TOKEN"):
            raise EnvironmentError("REPLICATE_API_TOKEN is not set")
        return replicate

    def _build_input(self, panel: Panel, output_cfg: OutputConfig, negative_prompt: str = "") -> dict:
        inp: dict = {
            "prompt": panel.visual_prompt,
            "num_outputs": 1,
            "output_format": output_cfg.format,
        }
        # Prefer aspect_ratio string; fall back to width/height
        if output_cfg.aspect_ratio:
            inp["aspect_ratio"] = output_cfg.aspect_ratio
        else:
            w, h = output_cfg.resolved_dimensions()
            inp["width"] = w
            inp["height"] = h
        if negative_prompt:
            inp["negative_prompt"] = negative_prompt
        if self.config.loras:
            inp["extra_loras"] = [
                {"url": lora.path, "scale": lora.strength}
                for lora in self.config.loras
            ]
            # Prepend trigger words to the prompt
            trigger_words = " ".join(
                lora.trigger_word for lora in self.config.loras if lora.trigger_word
            )
            if trigger_words:
                inp["prompt"] = f"{trigger_words}, {inp['prompt']}"
        return inp

    async def render_async(
        self,
        panel: Panel,
        output_dir: Path,
        output_cfg: OutputConfig,
        reference_images: dict[str, Path] | None = None,
        negative_prompt: str = "",
    ) -> RenderResult:
        import asyncio
        return await asyncio.get_event_loop().run_in_executor(
            None, self._render_sync, panel, output_dir, output_cfg, negative_prompt
        )

    def _render_sync(
        self, panel: Panel, output_dir: Path, output_cfg: OutputConfig, negative_prompt: str = ""
    ) -> RenderResult:
        import httpx
        replicate = self._client()

        if not self._model_cfg.model_ref:
            raise ValueError(
                "renderer.flux_klein.model_ref is not set. "
                "Set it to your Replicate model string (e.g. 'owner/model:version')."
            )

        inp = self._build_input(panel, output_cfg, negative_prompt)
        output = replicate.run(self._model_cfg.model_ref, input=inp)

        url = output[0] if isinstance(output[0], str) else output[0].url
        image_bytes = httpx.get(url).content

        out_path = output_dir / f"panel_{panel.panel_number:04d}.{output_cfg.format}"
        out_path.write_bytes(image_bytes)

        return RenderResult(
            panel_number=panel.panel_number,
            image_path=out_path,
            backend_used=self.model_spec.name,
            prompt_used=inp["prompt"],
            metadata={"model_ref": self._model_cfg.model_ref, "loras": len(self.config.loras)},
        )
