# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/',
                'doc_host': '',
                'git_url': 'https://github.com/HendrykPf/manhualizer',
                'lib_path': 'manhualizer'},
  'syms': {'manhualizer.core': {'manhualizer.core.foo': ('core.html#foo', 'manhualizer/core.py')}}}
