"""Generate reference sheet images for each character."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/09_character_sheets.ipynb.

# %% ../nbs/09_character_sheets.ipynb #cell-3
from __future__ import annotations
import asyncio
from pathlib import Path

from rich.console import Console
from rich.progress import Progress, SpinnerColumn, TextColumn

from .config import OutputConfig, PipelineConfig
from .models import Character, Panel, RenderResult, StoryAnalysis
from .prompts import TemplateSet, build_character_sheet_prompt
from .render import BaseRenderer

_console = Console()

# %% auto #0
__all__ = ['generate_character_sheets_async', 'generate_character_sheets']

# %% ../nbs/09_character_sheets.ipynb #cell-4
def _sheet_path(output_dir: Path, character: Character, fmt: str) -> Path:
    """Canonical path for a character's reference sheet image."""
    safe_name = character.name.lower().replace(" ", "_")
    return output_dir / f"{safe_name}.{fmt}"

# %% ../nbs/09_character_sheets.ipynb #cell-5
def _make_sheet_panel(character: Character, templates: TemplateSet, panel_number: int = 0) -> Panel:
    """Create a synthetic Panel representing a character reference sheet render.

    The visual_prompt is built from the character's reference_image_prompt
    using the active template's character_sheet_template.
    """
    # Use the character's existing reference_image_prompt as the description,
    # augmented with physical description for maximum detail.
    description = character.reference_image_prompt or character.physical_description
    if character.physical_description and character.physical_description not in description:
        description = f"{description}, {character.physical_description}"

    visual_prompt = build_character_sheet_prompt(
        templates, character_description=description
    )
    return Panel(
        panel_number=panel_number,
        scene_id="character_sheets",
        characters_present=[character.name],
        location="neutral background",
        action_description=f"Character reference sheet for {character.name}",
        visual_prompt=visual_prompt,
    )

# %% ../nbs/09_character_sheets.ipynb #cell-6
async def _generate_one(
    character: Character,
    renderer: BaseRenderer,
    output_dir: Path,
    output_cfg: OutputConfig,
    templates: TemplateSet,
    resume: bool,
    semaphore: asyncio.Semaphore,
    panel_number: int,
) -> tuple[str, Path]:
    """Generate (or resume) a single character sheet. Returns (character_name, image_path)."""
    out_path = _sheet_path(output_dir, character, output_cfg.format)

    if resume and out_path.exists():
        _console.print(f"[dim]character_sheets: skipping {character.name} (exists)[/dim]")
        return character.name, out_path

    sheet_panel = _make_sheet_panel(character, templates, panel_number)
    async with semaphore:
        result: RenderResult = await renderer.render_async(
            sheet_panel, output_dir, output_cfg, reference_images=None
        )
    # Rename from panel_XXXX.fmt to <character_name>.fmt
    if result.image_path != out_path:
        result.image_path.rename(out_path)
    return character.name, out_path

# %% ../nbs/09_character_sheets.ipynb #cell-7
async def generate_character_sheets_async(
    analysis: StoryAnalysis,
    renderer: BaseRenderer,
    output_dir: Path,
    templates: TemplateSet,
    config: PipelineConfig,
    concurrency: int = 2,
) -> dict[str, Path]:
    """Generate reference sheet images for all characters in the analysis.

    Only called when `renderer.model_spec.capabilities.reference_images` is True.
    Sheets are rendered concurrently up to `concurrency` at a time.

    Args:
        analysis: StoryAnalysis with the list of characters to render.
        renderer: Active renderer (must support reference_images).
        output_dir: Directory to write sheet images into.
        templates: Active TemplateSet (provides style + character_sheet_template).
        config: PipelineConfig (uses output and resume settings).
        concurrency: Max parallel renders.

    Returns:
        Dict mapping character name → image path.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    output_cfg = config.output

    _console.print(f"[bold]character_sheets:[/bold] generating {len(analysis.characters)} sheet(s)")

    sem = asyncio.Semaphore(concurrency)
    tasks = [
        _generate_one(char, renderer, output_dir, output_cfg, templates,
                      config.resume, sem, i)
        for i, char in enumerate(analysis.characters)
    ]

    results = await asyncio.gather(*tasks)
    sheets: dict[str, Path] = dict(results)

    _console.print(f"[green]character_sheets: {len(sheets)} sheet(s) ready[/green]")
    for name, path in sheets.items():
        _console.print(f"  {name}: {path}")

    return sheets


def generate_character_sheets(
    analysis: StoryAnalysis,
    renderer: BaseRenderer,
    output_dir: Path,
    templates: TemplateSet,
    config: PipelineConfig,
    concurrency: int = 2,
) -> dict[str, Path]:
    """Sync wrapper around generate_character_sheets_async."""
    return asyncio.run(
        generate_character_sheets_async(
            analysis, renderer, output_dir, templates, config, concurrency
        )
    )
