"""Pipeline configuration loaded from `manhualizer.yml` and/or environment variables."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_config.ipynb.

# %% ../nbs/01_config.ipynb #bd23d763
from __future__ import annotations
from pathlib import Path
from typing import Literal
from pydantic import BaseModel, Field
import yaml

# %% auto #0
__all__ = ['OutputConfig', 'LLMConfig', 'LoRAConfig', 'NanaBananaConfig', 'ChatGPTImageConfig', 'SeedreamConfig',
           'Seedream45Config', 'FluxKleinConfig', 'ComfyUIConfig', 'RendererConfig', 'PipelineConfig', 'load_config']

# %% ../nbs/01_config.ipynb #1d3f3bb3
class OutputConfig(BaseModel):
    """Controls the format and dimensions of rendered panel images."""
    dir: str = "output"
    format: Literal["png", "jpg", "webp"] = "png"
    width: int = 1024
    height: int = 1536
    """Default 2:3 ratio — standard vertical manhua format."""
    aspect_ratio: str | None = None
    """Optional aspect ratio string (e.g. '9:16'). Overrides width/height when set."""

    def resolved_dimensions(self) -> tuple[int, int]:
        """Return (width, height) respecting aspect_ratio if set."""
        if not self.aspect_ratio:
            return self.width, self.height
        w_ratio, h_ratio = [int(x) for x in self.aspect_ratio.split(":")]
        return self.width, int(self.width * h_ratio / w_ratio)

# %% ../nbs/01_config.ipynb #bddf69af
class LLMConfig(BaseModel):
    """LLM settings. Model string uses litellm format: 'provider/model'.

    API keys are read from environment variables — never stored here.
    Common choices:
    - "openrouter/moonshotai/kimi-k2"   → OPENROUTER_API_KEY  (default, best value)
    - "anthropic/claude-sonnet-4-6"     → ANTHROPIC_API_KEY   (high quality)
    - "anthropic/claude-haiku-4-5-20251001" → ANTHROPIC_API_KEY (fastest/cheapest)
    - "openai/gpt-4o"                   → OPENAI_API_KEY
    """
    model: str = "anthropic/claude-sonnet-4-6"
    temperature: float = 0.7
    max_tokens: int = 16384

# %% ../nbs/01_config.ipynb #7961791d
class LoRAConfig(BaseModel):
    """A LoRA weight to apply during image generation (model-dependent)."""
    path: str
    """URL, local path, or model identifier — interpretation depends on the backend."""
    strength: float = 0.8
    trigger_word: str = ""

# %% ../nbs/01_config.ipynb #d24cf604
class NanaBananaConfig(BaseModel):
    """Config for the NanaBanana (Google Imagen) backend."""
    model: str = "imagen-3.0-generate-002"
    location: str = "us-central1"
    """API key read from GOOGLE_API_KEY env var."""

# %% ../nbs/01_config.ipynb #d54164a5
class ChatGPTImageConfig(BaseModel):
    """Config for the OpenAI image generation backend."""
    model: str = "dall-e-3"
    quality: Literal["standard", "hd"] = "standard"
    """API key read from OPENAI_API_KEY env var."""

# %% ../nbs/01_config.ipynb #e5292305
class SeedreamConfig(BaseModel):
    """Config for the Seedream model (generic Replicate deployment)."""
    model_ref: str = ""
    """Model reference (e.g. Replicate model string). Set to your deployment."""

# %% ../nbs/01_config.ipynb #1bc69cgzr0e
class Seedream45Config(BaseModel):
    """Config for Seedream 4.5 (bytedance/seedream-4.5 on Replicate).
    
    The model endpoint is fixed — no model_ref needed.
    All generation parameters are derived from OutputConfig and the panel prompt.
    """
    pass

# %% ../nbs/01_config.ipynb #f8264ee6
class FluxKleinConfig(BaseModel):
    """Config for the Flux Klein 9B model."""
    model_ref: str = ""
    """Model reference (e.g. Replicate model string). Set to your deployment."""

# %% ../nbs/01_config.ipynb #8fa7178c
class ComfyUIConfig(BaseModel):
    """Config for a local ComfyUI server."""
    base_url: str = "http://127.0.0.1:8188"
    workflow_template_path: str = ""
    """Path to a ComfyUI workflow JSON (API format) for image generation (Step 1)."""
    speech_bubble_workflow_path: str = ""
    """Path to a ComfyUI workflow JSON for adding speech bubbles (Step 2). Optional."""
    poll_interval: float = 2.0
    timeout: float = 120.0

# %% ../nbs/01_config.ipynb #8656d202
class RendererConfig(BaseModel):
    """Image generation settings: which model to use and its parameters."""
    model: str = "comfyui"
    """Key into the model registry. One of: nanobanana, chatgpt-image, seedream, seedream-4.5, flux-klein, comfyui."""
    loras: list[LoRAConfig] = Field(default_factory=list)
    """LoRA weights to apply. Silently ignored for models that don't support LoRA."""
    nanobanana: NanaBananaConfig = Field(default_factory=NanaBananaConfig)
    chatgpt_image: ChatGPTImageConfig = Field(default_factory=ChatGPTImageConfig)
    seedream: SeedreamConfig = Field(default_factory=SeedreamConfig)
    seedream_45: Seedream45Config = Field(default_factory=Seedream45Config)
    flux_klein: FluxKleinConfig = Field(default_factory=FluxKleinConfig)
    comfyui: ComfyUIConfig = Field(default_factory=ComfyUIConfig)

# %% ../nbs/01_config.ipynb #77307c8a
class PipelineConfig(BaseModel):
    """Top-level configuration for a manhualizer run.
    
    Can be loaded from a `manhualizer.yml` file and/or overridden via CLI flags.
    """
    llm: LLMConfig = Field(default_factory=LLMConfig)
    renderer: RendererConfig = Field(default_factory=RendererConfig)
    output: OutputConfig = Field(default_factory=OutputConfig)
    template: str = "default"
    """Name of the prompt template set to use (built-in or from custom_templates_dir)."""
    custom_templates_dir: str | None = None
    """Path to a directory of custom template YAML files."""
    max_chunk_tokens: int = 3000
    storyboard_chunk_tokens: int = 1200
    """Max tokens per story chunk when building a storyboard scene.
    Smaller values → more scenes, fewer panels per scene, smaller LLM responses.
    ~1200 tokens ≈ 800 words ≈ 8–12 panels — safe within a single LLM response."""
    run_validation: bool = False
    """Run the optional LLM validation step (adds latency and cost)."""
    resume: bool = True
    """Skip steps whose output files already exist."""
    verbose: bool = True
    """Print per-panel timing lines during render and speech bubble steps."""


# %% ../nbs/01_config.ipynb #56d37f4a
def load_config(path: Path | str | None = None, **overrides) -> PipelineConfig:
    """Load PipelineConfig from a YAML file, then apply any keyword overrides.
    
    Lookup order:
    1. Defaults (PipelineConfig field defaults)
    2. YAML file at `path` (or `manhualizer.yml` in CWD if `path` is None and the file exists)
    3. `**overrides` keyword arguments (from CLI flags)
    
    API keys are **never** stored in YAML — set them as environment variables.
    """
    data: dict = {}

    if path is None:
        default_path = Path("manhualizer.yml")
        if default_path.exists():
            path = default_path

    if path is not None:
        with open(path) as f:
            data = yaml.safe_load(f) or {}

    # Apply CLI overrides as flat keys → nested structure
    _apply_overrides(data, overrides)

    return PipelineConfig.model_validate(data)


def _apply_overrides(data: dict, overrides: dict) -> None:
    """Merge flat CLI overrides into nested config dict. None values are ignored."""
    mapping = {
        "output_dir":      ("output", "dir"),
        "format":          ("output", "format"),
        "width":           ("output", "width"),
        "height":          ("output", "height"),
        "aspect_ratio":    ("output", "aspect_ratio"),
        "llm_model":       ("llm", "model"),
        "model":           ("renderer", "model"),
        "template":        ("template",),
        "resume":          ("resume",),
        "run_validation":  ("run_validation",),
        "verbose":         ("verbose",),
        "style_prefix":    None,  # handled via template system, not config
    }
    for key, value in overrides.items():
        if value is None:
            continue
        path = mapping.get(key)
        if path is None:
            continue
        node = data
        for part in path[:-1]:
            node = node.setdefault(part, {})
        node[path[-1]] = value
