"""LLM client wrapping litellm. Handles chunking, JSON extraction, and retries."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_llm.ipynb.

# %% ../nbs/03_llm.ipynb #cell-3
from __future__ import annotations
import json
import re
import textwrap
from typing import Any

import litellm
from .config import LLMConfig
from .prompts import TemplateSet

# %% auto #0
__all__ = ['chunk_story', 'extract_json', 'LLMClient']

# %% ../nbs/03_llm.ipynb #cell-5
def chunk_story(
    text: str,
    max_tokens: int = 3000,
    tokens_per_word: float = 1.4,
) -> list[str]:
    """Split story text into chunks that fit within `max_tokens`.

    Strategy (in order of preference):
    1. Split on double newlines (paragraph breaks)
    2. Split on single newlines
    3. Split on sentence boundaries ('. ', '! ', '? ')
    4. Hard word-count split as last resort

    Chunks are joined greedily until the token budget is exhausted.
    """
    max_words = int(max_tokens / tokens_per_word)

    # Try splits from coarsest to finest
    for separator in ["\n\n", "\n", r"(?<=[.!?]) +"]:
        parts = re.split(separator, text.strip())
        if len(parts) > 1:
            return _join_parts(parts, max_words)

    # Fallback: hard word-count split
    words = text.split()
    return [" ".join(words[i:i + max_words]) for i in range(0, len(words), max_words)]


def _join_parts(parts: list[str], max_words: int) -> list[str]:
    """Greedily join parts into chunks that don't exceed max_words."""
    chunks, current, current_words = [], [], 0
    for part in parts:
        part = part.strip()
        if not part:
            continue
        part_words = len(part.split())
        if current and current_words + part_words > max_words:
            chunks.append(" ".join(current))
            current, current_words = [], 0
        current.append(part)
        current_words += part_words
    if current:
        chunks.append(" ".join(current))
    return chunks

# %% ../nbs/03_llm.ipynb #cell-7
def extract_json(text: str) -> Any:
    """Extract and parse JSON from an LLM response.

    Handles responses that are:
    - Pure JSON
    - JSON wrapped in markdown fences (```json ... ```)
    - JSON embedded in surrounding prose

    Raises ValueError if no valid JSON can be found.
    """
    # Try direct parse first
    text = text.strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    # Strip markdown fences
    fenced = re.search(r"```(?:json)?\s*([\s\S]+?)\s*```", text)
    if fenced:
        try:
            return json.loads(fenced.group(1))
        except json.JSONDecodeError:
            pass

    # Find the largest {...} or [...] block
    for pattern in (r"(\{[\s\S]+\})", r"(\[[\s\S]+\])"):
        match = re.search(pattern, text)
        if match:
            try:
                return json.loads(match.group(1))
            except json.JSONDecodeError:
                pass

    raise ValueError(f"Could not extract JSON from LLM response:\n{text[:500]}")

# %% ../nbs/03_llm.ipynb #cell-9
class LLMClient:
    """Thin wrapper around litellm for manhualizer pipeline calls.

    All calls go through `complete()`. JSON responses are parsed via `complete_json()`.
    API keys are read from environment variables by litellm automatically.
    """

    def __init__(self, config: LLMConfig, templates: TemplateSet):
        self.config = config
        self.templates = templates
        litellm.drop_params = True  # ignore unsupported params per model

    def complete(
        self,
        user_prompt: str,
        system_prompt: str = "",
        temperature: float | None = None,
        max_tokens: int | None = None,
    ) -> str:
        """Call the LLM and return the response text."""
        messages = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": user_prompt})

        response = litellm.completion(
            model=self.config.model,
            messages=messages,
            temperature=temperature if temperature is not None else self.config.temperature,
            max_tokens=max_tokens if max_tokens is not None else self.config.max_tokens,
        )
        return response.choices[0].message.content

    def complete_json(
        self,
        user_prompt: str,
        system_prompt: str = "",
        retries: int = 2,
    ) -> Any:
        """Call the LLM and parse the response as JSON.

        Retries up to `retries` times on parse failure, asking the model to
        return only valid JSON.
        """
        last_error: Exception | None = None
        prompt = user_prompt
        for attempt in range(retries + 1):
            text = self.complete(prompt, system_prompt)
            try:
                return extract_json(text)
            except ValueError as e:
                last_error = e
                prompt = (
                    f"{user_prompt}\n\n"
                    f"Your previous response could not be parsed as JSON. "
                    f"Return ONLY valid JSON, no explanation, no markdown.\n"
                    f"Previous response (for reference):\n{text[:300]}"
                )
        raise ValueError(f"LLM failed to return valid JSON after {retries + 1} attempts: {last_error}")

    def complete_from_template(
        self,
        template_file: str,
        prompt_key: str,
        system_key: str = "system",
        as_json: bool = False,
        **variables: Any,
    ) -> str | Any:
        """Render a template and call the LLM.

        Args:
            template_file: YAML file name (e.g. 'analyze.yml')
            prompt_key: Key in the YAML for the user prompt template
            system_key: Key in the YAML for the system prompt (default 'system')
            as_json: If True, parse and return the response as JSON
            **variables: Template substitution variables
        """
        user_prompt = self.templates.render(template_file, prompt_key, **variables)
        try:
            system_prompt = self.templates.get(template_file, system_key)
        except KeyError:
            system_prompt = ""

        if as_json:
            return self.complete_json(user_prompt, system_prompt)
        return self.complete(user_prompt, system_prompt)
