"""Top-level pipeline orchestrator."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_pipeline.ipynb.

# %% ../nbs/10_pipeline.ipynb #cell-3
from __future__ import annotations
import asyncio
import time
from pathlib import Path

from rich.console import Console
from rich.rule import Rule

from .analyze import analyze_story
from .html import generate_html_viewer
from .character_sheets import generate_character_sheets_async
from .config import PipelineConfig
from .llm import LLMClient
from .models import ComicOutput, StoryAnalysis, Storyboard
from .prompts import load_templates
from .render import get_renderer
from .storyboard import build_storyboard
from .validate import validate_storyboard

_console = Console()

# %% auto #0
__all__ = ['run', 'run_analyze_only', 'run_storyboard_only', 'run_render_only', 'run_speech_bubbles']

# %% ../nbs/10_pipeline.ipynb #cell-4
_ANALYSIS_FILE = "analysis.json"
_STORYBOARD_FILE = "storyboard.json"


def _output_dir(config: PipelineConfig, story_path: Path) -> Path:
    """Resolve the output directory, defaulting to <story_stem>_comic/ next to the story."""
    if config.output.dir != "output":
        return Path(config.output.dir)
    return story_path.parent / f"{story_path.stem}_comic"


def _delete_panel_files(panels_dir: Path, panels: list, force_set: set) -> None:
    """Delete existing image files for panels whose number is in force_set."""
    for panel in panels:
        if panel.panel_number not in force_set:
            continue
        for ext in ("png", "jpg", "webp"):
            p = panels_dir / f"panel_{panel.panel_number:04d}.{ext}"
            if p.exists():
                p.unlink()
                # Also remove the pre-bubble backup so a fresh one is created
                # after the next render.
                raw = p.parent / (p.stem + ".raw" + p.suffix)
                if raw.exists():
                    raw.unlink()
                break



# %% ../nbs/10_pipeline.ipynb #cell-5
def run(
    story_path: str | Path,
    config: PipelineConfig | None = None,
) -> ComicOutput:
    """Run the full manhualizer pipeline.

    Steps:
    1. Analyze story text → analysis.json
    2. Build storyboard → storyboard.json
    3. Validate storyboard (optional, config.run_validation)
    4. Generate character sheets (only if model supports reference_images)
    5. Render all panels concurrently → panels/

    All intermediate results are persisted to disk. If `config.resume` is True
    (the default), completed steps are skipped on re-runs.

    Args:
        story_path: Path to the story text file.
        config: PipelineConfig. If None, defaults are used (looks for
                manhualizer.yml in the current directory).

    Returns:
        ComicOutput with paths to all generated files.
    """
    story_path = Path(story_path)
    if not story_path.exists():
        raise FileNotFoundError(f"Story file not found: {story_path}")

    if config is None:
        from manhualizer.config import load_config
        config = load_config()

    output_dir = _output_dir(config, story_path)
    output_dir.mkdir(parents=True, exist_ok=True)

    story_text = story_path.read_text(encoding="utf-8")

    templates = load_templates(config.template, config.custom_templates_dir)
    llm = LLMClient(config.llm, templates)
    renderer = get_renderer(config.renderer.model, config.renderer)

    total_steps = 3 + (1 if config.run_validation else 0) + (1 if renderer.model_spec.capabilities.reference_images else 0)
    step = 0

    def _step(label: str) -> float:
        nonlocal step
        step += 1
        _console.print(f"[bold][{step}/{total_steps}][/bold] {label}")
        return time.monotonic()

    def _done(t0: float, detail: str = "") -> None:
        elapsed = time.monotonic() - t0
        suffix = f"  [dim]{detail}[/dim]" if detail else ""
        _console.print(f"    [green]done[/green] in {elapsed:.1f}s{suffix}")

    _console.print(Rule(f"[bold]manhualizer[/bold] — {story_path.name}"))
    _console.print(f"  model: [cyan]{config.renderer.model}[/cyan]  "
                   f"template: [cyan]{config.template}[/cyan]  "
                   f"output: [cyan]{output_dir}[/cyan]")

    # ── Step 1: Analyze ──────────────────────────────────────────────────────
    t0 = _step("Analyzing story…")
    analysis = analyze_story(
        story_text, llm, config, output_dir / _ANALYSIS_FILE
    )
    _done(t0, f"{len(analysis.characters)} character(s), {len(analysis.locations)} location(s)")

    # ── Step 2: Storyboard ───────────────────────────────────────────────────
    t0 = _step("Building storyboard…")
    storyboard = build_storyboard(
        story_text, analysis, llm, templates, config, output_dir / _STORYBOARD_FILE
    )
    panel_count = len(storyboard.all_panels)
    _done(t0, f"{len(storyboard.scenes)} scene(s), {panel_count} panel(s)")

    # ── Step 3: Validate (optional) ──────────────────────────────────────────
    validation_path: Path | None = None
    if config.run_validation:
        t0 = _step("Validating storyboard…")
        validation_path = output_dir / "validation.json"
        validate_storyboard(story_text, storyboard, llm, config, validation_path)
        _done(t0)

    # ── Step 4: Character sheets (capability-gated) ───────────────────────────
    character_sheets: dict[str, Path] = {}
    if renderer.model_spec.capabilities.reference_images:
        t0 = _step("Generating character sheets…")
        character_sheets = asyncio.run(
            generate_character_sheets_async(
                analysis, renderer,
                output_dir / "character_sheets",
                templates, config,
            )
        )
        _done(t0, f"{len(character_sheets)} sheet(s)")

    # ── Step 5: Render panels ─────────────────────────────────────────────────
    t0 = _step(f"Rendering {panel_count} panel(s)…")
    panels_dir = output_dir / "panels"
    render_results = asyncio.run(
        renderer.render_batch_async(
            storyboard.all_panels,
            panels_dir,
            config.output,
            reference_images=character_sheets or None,
            resume=config.resume,
            verbose=config.verbose,
        )
    )
    _done(t0)

    result = ComicOutput(
        output_dir=output_dir,
        analysis_path=output_dir / _ANALYSIS_FILE,
        storyboard_path=output_dir / _STORYBOARD_FILE,
        validation_path=validation_path,
        rendered_panels=render_results,
    )

    result.html_path = generate_html_viewer(result, storyboard, title=analysis.title)

    _console.print(Rule())
    _console.print(f"[bold green]Done![/bold green] {len(render_results)} panel(s) → {output_dir}")
    _console.print(f"  [dim]viewer → {result.html_path}[/dim]")
    return result


# %% ../nbs/10_pipeline.ipynb #cell-6
def run_analyze_only(
    story_path: str | Path,
    config: PipelineConfig | None = None,
) -> StoryAnalysis:
    """Run only the analysis step and return the StoryAnalysis."""
    story_path = Path(story_path)
    if config is None:
        from manhualizer.config import load_config
        config = load_config()
    output_dir = _output_dir(config, story_path)
    output_dir.mkdir(parents=True, exist_ok=True)
    templates = load_templates(config.template, config.custom_templates_dir)
    llm = LLMClient(config.llm, templates)
    return analyze_story(
        story_path.read_text(encoding="utf-8"), llm, config, output_dir / _ANALYSIS_FILE
    )


def run_storyboard_only(
    story_path: str | Path,
    config: PipelineConfig | None = None,
) -> Storyboard:
    """Run analysis + storyboard steps. Resumes from analysis.json if available."""
    story_path = Path(story_path)
    if config is None:
        from manhualizer.config import load_config
        config = load_config()
    output_dir = _output_dir(config, story_path)
    output_dir.mkdir(parents=True, exist_ok=True)
    templates = load_templates(config.template, config.custom_templates_dir)
    llm = LLMClient(config.llm, templates)
    story_text = story_path.read_text(encoding="utf-8")
    analysis = analyze_story(story_text, llm, config, output_dir / _ANALYSIS_FILE)
    return build_storyboard(story_text, analysis, llm, templates, config, output_dir / _STORYBOARD_FILE)


def run_render_only(
    story_path: str | Path,
    config: PipelineConfig | None = None,
    rerender_panels: list[int] | None = None,
) -> ComicOutput:
    """Run render step only. Requires analysis.json and storyboard.json to exist.

    Args:
        story_path: Path to the story text file.
        config: PipelineConfig.
        rerender_panels: Optional list of panel numbers to force re-render.
                         Those specific panels are re-rendered even if their
                         image file already exists.
    """
    story_path = Path(story_path)
    if config is None:
        from manhualizer.config import load_config
        config = load_config()
    output_dir = _output_dir(config, story_path)

    analysis_path = output_dir / _ANALYSIS_FILE
    storyboard_path = output_dir / _STORYBOARD_FILE
    for p in (analysis_path, storyboard_path):
        if not p.exists():
            raise FileNotFoundError(
                f"{p} not found. Run `manhualizer storyboard-only` first."
            )

    templates = load_templates(config.template, config.custom_templates_dir)
    analysis = StoryAnalysis.model_validate_json(analysis_path.read_text())
    storyboard = Storyboard.model_validate_json(storyboard_path.read_text())
    renderer = get_renderer(config.renderer.model, config.renderer)

    character_sheets: dict[str, Path] = {}
    if renderer.model_spec.capabilities.reference_images:
        character_sheets = asyncio.run(
            generate_character_sheets_async(
                analysis, renderer, output_dir / "character_sheets", templates, config
            )
        )

    panels_dir = output_dir / "panels"

    if rerender_panels:
        force_set = set(rerender_panels)
        _console.print(f"  re-rendering panel(s): [cyan]{sorted(force_set)}[/cyan]")
        _delete_panel_files(panels_dir, storyboard.all_panels, force_set)

    render_results = asyncio.run(
        renderer.render_batch_async(
            storyboard.all_panels, panels_dir,
            config.output, reference_images=character_sheets or None,
            resume=config.resume,
            verbose=config.verbose,
        )
    )
    return ComicOutput(
        output_dir=output_dir,
        analysis_path=analysis_path,
        storyboard_path=storyboard_path,
        rendered_panels=render_results,
    )


def run_speech_bubbles(
    story_path: str | Path,
    config: PipelineConfig | None = None,
    rerender_panels: list[int] | None = None,
) -> list:
    """Apply speech bubbles to already-rendered panels via ComfyUI.

    Requires ``panels/`` to exist (run the render step first).  Reads dialogue
    data from ``storyboard.json``, runs the speech bubble workflow on each panel
    that has dialogue, and overwrites the panel images in-place.

    Args:
        story_path: Path to the original story text file.
        config: PipelineConfig. Must have
                ``renderer.comfyui.speech_bubble_workflow_path`` set.
        rerender_panels: Optional list of panel numbers to force re-process,
                         ignoring existing ``.bubbles_done`` markers.

    Returns:
        List of Path objects for every panel image that was updated.

    Raises:
        FileNotFoundError: If storyboard.json or the speech bubble workflow is missing.
    """
    story_path = Path(story_path)
    if config is None:
        from manhualizer.config import load_config
        config = load_config()

    output_dir = _output_dir(config, story_path)
    storyboard_path = output_dir / _STORYBOARD_FILE
    if not storyboard_path.exists():
        raise FileNotFoundError(
            f"{storyboard_path} not found. Run `manhualizer render-only` first."
        )

    storyboard = Storyboard.model_validate_json(storyboard_path.read_text())
    panels_dir = output_dir / "panels"

    templates = load_templates(config.template, config.custom_templates_dir)
    try:
        bubble_types: dict = templates._load("bubble_types.yml")
    except FileNotFoundError:
        bubble_types = {}

    from .renderers.comfyui import ComfyUIRenderer
    from .render import MODELS
    renderer = ComfyUIRenderer(MODELS["comfyui"], config.renderer)

    # When specific panels are requested, pass only those — keeps the progress total accurate.
    if rerender_panels:
        force_set = set(rerender_panels)
        _console.print(f"  re-processing bubble(s) for panel(s): [cyan]{sorted(force_set)}[/cyan]")
        panels_to_process = [p for p in storyboard.all_panels if p.panel_number in force_set]
        resume_flag = False
    else:
        panels_to_process = storyboard.all_panels
        resume_flag = config.resume

    _console.print(Rule("[bold]manhualizer[/bold] — add speech bubbles"))
    _console.print(f"  workflow: [cyan]{config.renderer.comfyui.speech_bubble_workflow_path}[/cyan]")
    _console.print(f"  panels:   [cyan]{panels_dir}[/cyan]")

    t0 = time.monotonic()
    updated = asyncio.run(
        renderer.add_speech_bubbles_batch_async(
            panels_to_process,
            panels_dir,
            resume=resume_flag,
            bubble_types=bubble_types,
            verbose=config.verbose,
        )
    )
    elapsed = time.monotonic() - t0
    _console.print(Rule())
    _console.print(
        f"[bold green]Done![/bold green] {len(updated)} panel(s) updated in {elapsed:.1f}s"
    )
    return updated
