"""Top-level pipeline orchestrator."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_pipeline.ipynb.

# %% ../nbs/10_pipeline.ipynb #cell-3
from __future__ import annotations
import asyncio
import time
from pathlib import Path

from rich.console import Console
from rich.rule import Rule

from .analyze import analyze_story
from .character_sheets import generate_character_sheets_async
from .config import PipelineConfig
from .llm import LLMClient
from .models import ComicOutput, StoryAnalysis, Storyboard
from .prompts import load_templates
from .render import get_renderer
from .storyboard import build_storyboard
from .validate import validate_storyboard

_console = Console()


# %% auto #0
__all__ = ['run', 'run_analyze_only', 'run_storyboard_only', 'run_render_only']

# %% ../nbs/10_pipeline.ipynb #cell-4
def _output_dir(config: PipelineConfig, story_path: Path) -> Path:
    """Resolve the output directory, defaulting to <story_stem>_comic/ next to the story."""
    if config.output.dir != "output":
        return Path(config.output.dir)
    return story_path.parent / f"{story_path.stem}_comic"

# %% ../nbs/10_pipeline.ipynb #cell-5
def run(
    story_path: str | Path,
    config: PipelineConfig | None = None,
) -> ComicOutput:
    """Run the full manhualizer pipeline.

    Steps:
    1. Analyze story text → analysis.json
    2. Build storyboard → storyboard.json
    3. Validate storyboard (optional, config.run_validation)
    4. Generate character sheets (only if model supports reference_images)
    5. Render all panels concurrently → panels/

    All intermediate results are persisted to disk. If `config.resume` is True
    (the default), completed steps are skipped on re-runs.

    Args:
        story_path: Path to the story text file.
        config: PipelineConfig. If None, defaults are used (looks for
                manhualizer.yml in the current directory).

    Returns:
        ComicOutput with paths to all generated files.
    """
    story_path = Path(story_path)
    if not story_path.exists():
        raise FileNotFoundError(f"Story file not found: {story_path}")

    if config is None:
        from manhualizer.config import load_config
        config = load_config()

    output_dir = _output_dir(config, story_path)
    output_dir.mkdir(parents=True, exist_ok=True)

    story_text = story_path.read_text(encoding="utf-8")

    templates = load_templates(config.template, config.custom_templates_dir)
    llm = LLMClient(config.llm, templates)
    renderer = get_renderer(config.renderer.model, config.renderer)

    total_steps = 3 + (1 if config.run_validation else 0) + (1 if renderer.model_spec.capabilities.reference_images else 0)
    step = 0

    def _step(label: str) -> float:
        nonlocal step
        step += 1
        _console.print(f"[bold][{step}/{total_steps}][/bold] {label}")
        return time.monotonic()

    def _done(t0: float, detail: str = "") -> None:
        elapsed = time.monotonic() - t0
        suffix = f"  [dim]{detail}[/dim]" if detail else ""
        _console.print(f"    [green]done[/green] in {elapsed:.1f}s{suffix}")

    _console.print(Rule(f"[bold]manhualizer[/bold] — {story_path.name}"))
    _console.print(f"  model: [cyan]{config.renderer.model}[/cyan]  "
                   f"template: [cyan]{config.template}[/cyan]  "
                   f"output: [cyan]{output_dir}[/cyan]")

    # ── Step 1: Analyze ──────────────────────────────────────────────────────
    t0 = _step("Analyzing story…")
    analysis = analyze_story(
        story_text, llm, config, output_dir / "analysis.json"
    )
    _done(t0, f"{len(analysis.characters)} character(s), {len(analysis.locations)} location(s)")

    # ── Step 2: Storyboard ───────────────────────────────────────────────────
    t0 = _step("Building storyboard…")
    storyboard = build_storyboard(
        story_text, analysis, llm, templates, config, output_dir / "storyboard.json"
    )
    panel_count = len(storyboard.all_panels)
    _done(t0, f"{len(storyboard.scenes)} scene(s), {panel_count} panel(s)")

    # ── Step 3: Validate (optional) ──────────────────────────────────────────
    validation_path: Path | None = None
    if config.run_validation:
        t0 = _step("Validating storyboard…")
        validation_path = output_dir / "validation.json"
        validate_storyboard(story_text, storyboard, llm, config, validation_path)
        _done(t0)

    # ── Step 4: Character sheets (capability-gated) ───────────────────────────
    character_sheets: dict[str, Path] = {}
    if renderer.model_spec.capabilities.reference_images:
        t0 = _step("Generating character sheets…")
        character_sheets = asyncio.run(
            generate_character_sheets_async(
                analysis, renderer,
                output_dir / "character_sheets",
                templates, config,
            )
        )
        _done(t0, f"{len(character_sheets)} sheet(s)")

    # ── Step 5: Render panels ─────────────────────────────────────────────────
    t0 = _step(f"Rendering {panel_count} panel(s)…")
    panels_dir = output_dir / "panels"
    render_results = asyncio.run(
        renderer.render_batch_async(
            storyboard.all_panels,
            panels_dir,
            config.output,
            reference_images=character_sheets or None,
            resume=config.resume,
        )
    )
    _done(t0)

    result = ComicOutput(
        output_dir=output_dir,
        analysis_path=output_dir / "analysis.json",
        storyboard_path=output_dir / "storyboard.json",
        validation_path=validation_path,
        rendered_panels=render_results,
    )

    _console.print(Rule())
    _console.print(f"[bold green]Done![/bold green] {len(render_results)} panel(s) → {output_dir}")
    return result


# %% ../nbs/10_pipeline.ipynb #cell-6
def run_analyze_only(
    story_path: str | Path,
    config: PipelineConfig | None = None,
) -> StoryAnalysis:
    """Run only the analysis step and return the StoryAnalysis."""
    story_path = Path(story_path)
    if config is None:
        from manhualizer.config import load_config
        config = load_config()
    output_dir = _output_dir(config, story_path)
    output_dir.mkdir(parents=True, exist_ok=True)
    templates = load_templates(config.template, config.custom_templates_dir)
    llm = LLMClient(config.llm, templates)
    return analyze_story(
        story_path.read_text(encoding="utf-8"), llm, config, output_dir / "analysis.json"
    )


def run_storyboard_only(
    story_path: str | Path,
    config: PipelineConfig | None = None,
) -> Storyboard:
    """Run analysis + storyboard steps. Resumes from analysis.json if available."""
    story_path = Path(story_path)
    if config is None:
        from manhualizer.config import load_config
        config = load_config()
    output_dir = _output_dir(config, story_path)
    output_dir.mkdir(parents=True, exist_ok=True)
    templates = load_templates(config.template, config.custom_templates_dir)
    llm = LLMClient(config.llm, templates)
    story_text = story_path.read_text(encoding="utf-8")
    analysis = analyze_story(story_text, llm, config, output_dir / "analysis.json")
    return build_storyboard(story_text, analysis, llm, templates, config, output_dir / "storyboard.json")


def run_render_only(
    story_path: str | Path,
    config: PipelineConfig | None = None,
) -> ComicOutput:
    """Run render step only. Requires analysis.json and storyboard.json to exist."""
    story_path = Path(story_path)
    if config is None:
        from manhualizer.config import load_config
        config = load_config()
    output_dir = _output_dir(config, story_path)

    analysis_path = output_dir / "analysis.json"
    storyboard_path = output_dir / "storyboard.json"
    for p in (analysis_path, storyboard_path):
        if not p.exists():
            raise FileNotFoundError(
                f"{p} not found. Run `manhualizer storyboard-only` first."
            )

    templates = load_templates(config.template, config.custom_templates_dir)
    analysis = StoryAnalysis.model_validate_json(analysis_path.read_text())
    storyboard = Storyboard.model_validate_json(storyboard_path.read_text())
    renderer = get_renderer(config.renderer.model, config.renderer)

    character_sheets: dict[str, Path] = {}
    if renderer.model_spec.capabilities.reference_images:
        character_sheets = asyncio.run(
            generate_character_sheets_async(
                analysis, renderer, output_dir / "character_sheets", templates, config
            )
        )

    render_results = asyncio.run(
        renderer.render_batch_async(
            storyboard.all_panels, output_dir / "panels",
            config.output, reference_images=character_sheets or None,
            resume=config.resume,
        )
    )
    return ComicOutput(
        output_dir=output_dir,
        analysis_path=analysis_path,
        storyboard_path=storyboard_path,
        rendered_panels=render_results,
    )
