"""Prompt template loading and variable substitution."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_prompts.ipynb.

# %% ../nbs/02_prompts.ipynb #cell-3
from __future__ import annotations
from pathlib import Path
from typing import Any
import yaml

# %% auto #0
__all__ = ['TemplateSet', 'load_templates', 'list_builtin_templates', 'build_panel_prompt', 'build_character_sheet_prompt']

# %% ../nbs/02_prompts.ipynb #cell-4
# Built-in templates ship inside the package
_BUILTIN_TEMPLATES_DIR = Path(__file__).parent / "templates"

# %% ../nbs/02_prompts.ipynb #cell-5
class TemplateSet:
    """A loaded set of prompt templates from one directory.
    
    Template files are YAML. String values support `{variable}` substitution
    via `render(key, **vars)`. Missing variables leave the placeholder intact.
    """

    def __init__(self, templates_dir: Path):
        self._dir = templates_dir
        self._cache: dict[str, dict] = {}

    def _load(self, filename: str) -> dict:
        if filename not in self._cache:
            path = self._dir / filename
            if not path.exists():
                raise FileNotFoundError(f"Template not found: {path}")
            with open(path) as f:
                self._cache[filename] = yaml.safe_load(f) or {}
        return self._cache[filename]

    def get(self, filename: str, key: str) -> str:
        """Return the raw template string for `key` in `filename`."""
        data = self._load(filename)
        if key not in data:
            raise KeyError(f"Key '{key}' not found in template '{filename}'")
        return data[key]

    def render(self, filename: str, key: str, **variables: Any) -> str:
        """Return the template string with `{variable}` placeholders substituted."""
        template = self.get(filename, key)
        return _safe_substitute(template, variables)

    # Convenience accessors for the main template files
    @property
    def image_style(self) -> dict:
        return self._load("image_style.yml")

    @property
    def style_prefix(self) -> str:
        return self.image_style.get("style_prefix", "")

    @property
    def negative_prompt(self) -> str:
        return self.image_style.get("negative_prompt", "")

# %% ../nbs/02_prompts.ipynb #cell-6
import re

def _safe_substitute(template: str, variables: dict) -> str:
    """Substitute only simple `{identifier}` placeholders; leave all else intact.
    
    Unlike str.format_map(), this never recurses into complex `{...}` blocks
    (e.g. literal JSON examples in prompt templates).
    """
    def _replace(m: re.Match) -> str:
        key = m.group(1)
        return str(variables[key]) if key in variables else m.group(0)
    return re.sub(r'\{(\w+)\}', _replace, template)

# %% ../nbs/02_prompts.ipynb #cell-7
def load_templates(
    template_name: str = "default",
    custom_dir: str | Path | None = None,
) -> TemplateSet:
    """Load a TemplateSet by name.

    Resolution order:
    1. `custom_dir/<template_name>/` if provided
    2. Built-in `manhualizer/templates/<template_name>/`

    For style-only custom templates (e.g. a custom `image_style.yml`),
    individual files fall back to the `default` built-in template.
    """
    if custom_dir is not None:
        candidate = Path(custom_dir) / template_name
        if candidate.is_dir():
            return TemplateSet(candidate)

    builtin = _BUILTIN_TEMPLATES_DIR / template_name
    if not builtin.is_dir():
        raise ValueError(
            f"Unknown template '{template_name}'. "
            f"Built-in options: {list_builtin_templates()}"
        )
    return TemplateSet(builtin)


def list_builtin_templates() -> list[str]:
    """Return the names of all built-in template sets."""
    return sorted(p.name for p in _BUILTIN_TEMPLATES_DIR.iterdir() if p.is_dir())

# %% ../nbs/02_prompts.ipynb #cell-8
def build_panel_prompt(
    templates: TemplateSet,
    *,
    location_prompt: str,
    character_prompts: str,
    action: str,
    mood: str,
) -> str:
    """Assemble a final image-gen prompt for a single panel."""
    template = templates.image_style.get("panel_template", "{style_prefix}, {location_prompt}, {character_prompts}, {action}, {mood}")
    return template.format(
        style_prefix=templates.style_prefix,
        location_prompt=location_prompt,
        character_prompts=character_prompts,
        action=action,
        mood=mood,
    )


def build_character_sheet_prompt(
    templates: TemplateSet,
    *,
    character_description: str,
) -> str:
    """Assemble an image-gen prompt for a character reference sheet."""
    template = templates.image_style.get(
        "character_sheet_template",
        "{style_prefix}, character reference sheet, full body, {character_description}",
    )
    return template.format(
        style_prefix=templates.style_prefix,
        character_description=character_description,
    )
