"""Storyboard generation: convert story chunks into comic scenes and panels."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_storyboard.ipynb.

# %% ../nbs/05_storyboard.ipynb #cell-3
from __future__ import annotations
import json
from pathlib import Path

from rich.console import Console
from rich.progress import Progress, SpinnerColumn, TextColumn

from .config import PipelineConfig
from .llm import LLMClient
from manhualizer.models import (
    DialogueBubble, Panel, Scene, Storyboard, StoryAnalysis,
)
from .prompts import TemplateSet

_console = Console()

# %% auto #0
__all__ = ['build_storyboard']

# %% ../nbs/05_storyboard.ipynb #cell-5
def _character_lookup(analysis: StoryAnalysis) -> dict[str, str]:
    """Build a name → reference_image_prompt map (case-insensitive keys)."""
    return {
        c.name.lower(): c.reference_image_prompt
        for c in analysis.characters
        if c.reference_image_prompt
    }


def _location_lookup(analysis: StoryAnalysis) -> dict[str, str]:
    """Build a name → visual_prompt map (case-insensitive keys)."""
    return {
        l.name.lower(): l.visual_prompt
        for l in analysis.locations
        if l.visual_prompt
    }


def _dialogue_instructions(panel_data: dict) -> str:
    """Build image prompt instructions for dialogue bubbles.

    Tells the image model to render text inside speech/thought/caption bubbles
    directly in the image so panels are self-contained for vertical scrolling.
    """
    dialogue = panel_data.get("dialogue", [])
    if not dialogue:
        return ""

    parts = []
    for d in dialogue:
        bubble = d.get("bubble_type", "speech")
        speaker = d.get("speaker", "")
        text = d.get("text", "")
        if not text:
            continue

        if bubble == "caption" or speaker == "narration":
            parts.append(f'narration box with text "{text}"')
        elif bubble == "thought":
            parts.append(f'thought bubble from {speaker} saying "{text}"')
        elif bubble == "sfx":
            parts.append(f'bold sound effect text "{text}"')
        else:
            parts.append(f'speech bubble from {speaker} saying "{text}"')

    if not parts:
        return ""
    return "Contains: " + "; ".join(parts) + "."


def _assemble_visual_prompt(
    panel_data: dict,
    templates: TemplateSet,
    char_prompts: dict[str, str],
    loc_prompts: dict[str, str],
) -> str:
    """Assemble the final image-gen prompt for a panel.

    If the LLM already produced a complete visual_prompt, use it directly.
    Otherwise build from parts using the style template.
    Dialogue bubble instructions are always appended so panels are self-contained.
    """
    dialogue_part = _dialogue_instructions(panel_data)

    # Use LLM-provided prompt if present and substantial
    llm_prompt = panel_data.get("visual_prompt", "").strip()
    if llm_prompt and len(llm_prompt) > 20:
        # Ensure style prefix is prepended if missing
        style = templates.style_prefix
        if style and not llm_prompt.lower().startswith(style[:15].lower()):
            base = f"{style}, {llm_prompt}"
        else:
            base = llm_prompt
        return f"{base}. {dialogue_part}" if dialogue_part else base

    # Build from parts
    location_name = panel_data.get("location", "").lower()
    location_prompt = loc_prompts.get(location_name, location_name)

    chars_present = [c.lower() for c in panel_data.get("characters_present", [])]
    char_prompt_parts = [char_prompts[c] for c in chars_present if c in char_prompts]
    character_prompts = ", ".join(char_prompt_parts) if char_prompt_parts else "no characters"

    action = panel_data.get("action_description", "")
    mood = panel_data.get("mood", "")
    camera = panel_data.get("camera_angle", "")

    style_prefix = templates.style_prefix
    parts = [p for p in [style_prefix, location_prompt, character_prompts, action, mood, camera] if p]
    base = ", ".join(parts)
    return f"{base}. {dialogue_part}" if dialogue_part else base

# %% ../nbs/05_storyboard.ipynb #cell-7
def _parse_panel(
    data: dict,
    panel_number: int,
    scene_id: str,
    templates: TemplateSet,
    char_prompts: dict[str, str],
    loc_prompts: dict[str, str],
) -> Panel:
    dialogue = [
        DialogueBubble(
            speaker=d.get("speaker", ""),
            text=d.get("text", ""),
            bubble_type=d.get("bubble_type", "speech"),
        )
        for d in data.get("dialogue", [])
    ]
    visual_prompt = _assemble_visual_prompt(data, templates, char_prompts, loc_prompts)
    return Panel(
        panel_number=panel_number,
        scene_id=scene_id,
        characters_present=data.get("characters_present", []),
        location=data.get("location", ""),
        action_description=data.get("action_description", ""),
        visual_prompt=visual_prompt,
        dialogue=dialogue,
        mood=data.get("mood", ""),
        camera_angle=data.get("camera_angle", ""),
    )


def _parse_scene(
    data: dict,
    scene_index: int,
    panel_offset: int,
    chunk: str,
    templates: TemplateSet,
    char_prompts: dict[str, str],
    loc_prompts: dict[str, str],
) -> Scene:
    scene_id = data.get("scene_id", f"s{scene_index + 1}")
    panels = [
        _parse_panel(
            p, panel_offset + i + 1, scene_id,
            templates, char_prompts, loc_prompts,
        )
        for i, p in enumerate(data.get("panels", []))
    ]
    return Scene(
        scene_id=scene_id,
        title=data.get("title", f"Scene {scene_index + 1}"),
        source_chunk=chunk,
        panels=panels,
    )

# %% ../nbs/05_storyboard.ipynb #cell-9
def build_storyboard(
    story_text: str,
    analysis: StoryAnalysis,
    llm: LLMClient,
    templates: TemplateSet,
    config: PipelineConfig,
    output_path: Path,
) -> Storyboard:
    """Convert a story into a comic storyboard.

    Each chunk of the story text becomes one Scene. The LLM is given the full
    story analysis (characters, locations, style) so it can produce consistent,
    analysis-grounded panel descriptions and visual prompts.

    Visual prompts are assembled by prepending the style prefix from the active
    template and injecting the character/location reference prompts from the
    analysis. This keeps image generation prompts consistent across the whole comic.

    If `output_path` already exists and `config.resume` is True, the saved
    storyboard is returned without any LLM calls.

    Args:
        story_text: Full raw story text (same as passed to analyze_story).
        analysis: Output of analyze_story().
        llm: Configured LLMClient.
        templates: Active TemplateSet.
        config: PipelineConfig.
        output_path: Where to save storyboard.json.

    Returns:
        Storyboard with all scenes and panels populated.
    """
    output_path = Path(output_path)

    if config.resume and output_path.exists():
        _console.print(f"[dim]storyboard: resuming from {output_path}[/dim]")
        return Storyboard.model_validate_json(output_path.read_text())

    # Use chunks from the analysis so chunking is consistent
    chunks = analysis.source_chunks or [story_text]
    char_prompts = _character_lookup(analysis)
    loc_prompts = _location_lookup(analysis)
    analysis_json = analysis.model_dump_json(indent=2, exclude_none=True)

    _console.print(f"[bold]storyboard:[/bold] generating {len(chunks)} scene(s)")

    scenes: list[Scene] = []
    panel_offset = 0

    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        console=_console,
        transient=True,
    ) as progress:
        task = progress.add_task("Building storyboard...", total=len(chunks))

        for i, chunk in enumerate(chunks):
            progress.update(task, description=f"Scene {i + 1}/{len(chunks)}...")
            scene_data = llm.complete_from_template(
                "storyboard.yml",
                "storyboard_prompt",
                as_json=True,
                story_chunk=chunk,
                analysis=analysis_json,
                style_prefix=templates.style_prefix,
                panels_per_scene=config.panels_per_scene,
                scene_number=i + 1,
            )
            scene = _parse_scene(
                scene_data, i, panel_offset, chunk,
                templates, char_prompts, loc_prompts,
            )
            scenes.append(scene)
            panel_offset += len(scene.panels)
            progress.advance(task)

    storyboard = Storyboard(
        title=analysis.title,
        scenes=scenes,
        total_panels=panel_offset,
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(storyboard.model_dump_json(indent=2, exclude_none=True))
    _console.print(f"[green]storyboard: saved to {output_path}[/green]")
    _console.print(
        f"  {len(scenes)} scene(s), {panel_offset} panel(s) total"
    )

    return storyboard
